spring.application.name=backend
server.port=${PORT:8080}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/mangacloud_db}
spring.jackson.time-zone=Asia/Ho_Chi_Minh

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}